import { Inter } from "next/font/google";
import DeleteBlock from "./(components)/DeleteBlock";
import Nav from "./(components)/Nav";
import "./globals.css";

// import { config } from "@fortawesome/free-solid-svg-core"
// import "@fortawesome/free-solid-svg-core/styles.css"

// config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ticket App",
  description: "Generated by Hitman",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen max-h-screen">
          <Nav />
          <div className="flex-grow overflow-y-auto bg-page text-default-text">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
